//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace delivery_website.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public SharedResources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("delivery_website.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the terms of service and privacy policy.
        /// </summary>
        public static string Account_AgreeToTerms {
            get {
                return ResourceManager.GetString("Account.AgreeToTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the.
        /// </summary>
        public static string Account_AgreeToTermsPart1 {
            get {
                return ResourceManager.GetString("Account.AgreeToTermsPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string Account_And {
            get {
                return ResourceManager.GetString("Account.And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Login.
        /// </summary>
        public static string Account_BackToLogin {
            get {
                return ResourceManager.GetString("Account.BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Account_ConfirmPassword {
            get {
                return ResourceManager.GetString("Account.ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        public static string Account_ConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("Account.ConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Account_Email {
            get {
                return ResourceManager.GetString("Account.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your@email.com.
        /// </summary>
        public static string Account_EmailPlaceholder {
            get {
                return ResourceManager.GetString("Account.EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Account_FirstName {
            get {
                return ResourceManager.GetString("Account.FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John.
        /// </summary>
        public static string Account_FirstNamePlaceholder {
            get {
                return ResourceManager.GetString("Account.FirstNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Account_ForgotPassword {
            get {
                return ResourceManager.GetString("Account.ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t worry! Enter your email address and we&apos;ll send you a link to reset your password..
        /// </summary>
        public static string Account_ForgotPasswordText {
            get {
                return ResourceManager.GetString("Account.ForgotPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string Account_ForgotPasswordTitle {
            get {
                return ResourceManager.GetString("Account.ForgotPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string Account_HaveAccount {
            get {
                return ResourceManager.GetString("Account.HaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Account_LastName {
            get {
                return ResourceManager.GetString("Account.LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doe.
        /// </summary>
        public static string Account_LastNamePlaceholder {
            get {
                return ResourceManager.GetString("Account.LastNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Account_Login {
            get {
                return ResourceManager.GetString("Account.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Account_LoginButton {
            get {
                return ResourceManager.GetString("Account.LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to your account.
        /// </summary>
        public static string Account_LoginSubtitle {
            get {
                return ResourceManager.GetString("Account.LoginSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to System.
        /// </summary>
        public static string Account_LoginTitle {
            get {
                return ResourceManager.GetString("Account.LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string Account_NewPassword {
            get {
                return ResourceManager.GetString("Account.NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string Account_NoAccount {
            get {
                return ResourceManager.GetString("Account.NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Account_Password {
            get {
                return ResourceManager.GetString("Account.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters.
        /// </summary>
        public static string Account_PasswordHint {
            get {
                return ResourceManager.GetString("Account.PasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 6 characters.
        /// </summary>
        public static string Account_PasswordMinLength {
            get {
                return ResourceManager.GetString("Account.PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        public static string Account_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("Account.PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Account_PhoneNumber {
            get {
                return ResourceManager.GetString("Account.PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1XXXXXXXXXX.
        /// </summary>
        public static string Account_PhoneNumberPlaceholder {
            get {
                return ResourceManager.GetString("Account.PhoneNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy policy.
        /// </summary>
        public static string Account_PrivacyPolicy {
            get {
                return ResourceManager.GetString("Account.PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Account_Register {
            get {
                return ResourceManager.GetString("Account.Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Account_RegisterButton {
            get {
                return ResourceManager.GetString("Account.RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your account.
        /// </summary>
        public static string Account_RegisterSubtitle {
            get {
                return ResourceManager.GetString("Account.RegisterSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Account_RegisterTitle {
            get {
                return ResourceManager.GetString("Account.RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Account_RememberMe {
            get {
                return ResourceManager.GetString("Account.RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string Account_RequiredField {
            get {
                return ResourceManager.GetString("Account.RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string Account_ResetPassword {
            get {
                return ResourceManager.GetString("Account.ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Link.
        /// </summary>
        public static string Account_SendLink {
            get {
                return ResourceManager.GetString("Account.SendLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terms of service.
        /// </summary>
        public static string Account_TermsOfService {
            get {
                return ResourceManager.GetString("Account.TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Admin_All {
            get {
                return ResourceManager.GetString("Admin.All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Orders.
        /// </summary>
        public static string Admin_AllOrders {
            get {
                return ResourceManager.GetString("Admin.AllOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all verified.
        /// </summary>
        public static string Admin_AllVerified {
            get {
                return ResourceManager.GetString("Admin.AllVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Admin_Amount {
            get {
                return ResourceManager.GetString("Admin.Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Rating.
        /// </summary>
        public static string Admin_AverageRating {
            get {
                return ResourceManager.GetString("Admin.AverageRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Today.
        /// </summary>
        public static string Admin_CompletedToday {
            get {
                return ResourceManager.GetString("Admin.CompletedToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Admin_Customer {
            get {
                return ResourceManager.GetString("Admin.Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Admin_Dashboard {
            get {
                return ResourceManager.GetString("Admin.Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Admin_Date {
            get {
                return ResourceManager.GetString("Admin.Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new today.
        /// </summary>
        public static string Admin_NewToday {
            get {
                return ResourceManager.GetString("Admin.NewToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Users.
        /// </summary>
        public static string Admin_NewUsers {
            get {
                return ResourceManager.GetString("Admin.NewUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new users.
        /// </summary>
        public static string Admin_NoNewUsers {
            get {
                return ResourceManager.GetString("Admin.NoNewUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No orders.
        /// </summary>
        public static string Admin_NoOrders {
            get {
                return ResourceManager.GetString("Admin.NoOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reviews.
        /// </summary>
        public static string Admin_NoReviews {
            get {
                return ResourceManager.GetString("Admin.NoReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pending approval.
        /// </summary>
        public static string Admin_OnModeration {
            get {
                return ResourceManager.GetString("Admin.OnModeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Approval.
        /// </summary>
        public static string Admin_OnModerationReviews {
            get {
                return ResourceManager.GetString("Admin.OnModerationReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order #.
        /// </summary>
        public static string Admin_OrderNumber {
            get {
                return ResourceManager.GetString("Admin.OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Admin_Orders {
            get {
                return ResourceManager.GetString("Admin.Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders Today.
        /// </summary>
        public static string Admin_OrdersToday {
            get {
                return ResourceManager.GetString("Admin.OrdersToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pending.
        /// </summary>
        public static string Admin_Pending {
            get {
                return ResourceManager.GetString("Admin.Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Orders.
        /// </summary>
        public static string Admin_RecentOrders {
            get {
                return ResourceManager.GetString("Admin.RecentOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Reviews.
        /// </summary>
        public static string Admin_RecentReviews {
            get {
                return ResourceManager.GetString("Admin.RecentReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        public static string Admin_Restaurant {
            get {
                return ResourceManager.GetString("Admin.Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurants.
        /// </summary>
        public static string Admin_Restaurants {
            get {
                return ResourceManager.GetString("Admin.Restaurants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        public static string Admin_Revenue {
            get {
                return ResourceManager.GetString("Admin.Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews Pending Approval.
        /// </summary>
        public static string Admin_ReviewsOnModeration {
            get {
                return ResourceManager.GetString("Admin.ReviewsOnModeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Admin_Status {
            get {
                return ResourceManager.GetString("Admin.Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System overview and statistics.
        /// </summary>
        public static string Admin_SystemOverview {
            get {
                return ResourceManager.GetString("Admin.SystemOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string Admin_Today {
            get {
                return ResourceManager.GetString("Admin.Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Admin_Users {
            get {
                return ResourceManager.GetString("Admin.Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart cleared.
        /// </summary>
        public static string Cart_CartCleared {
            get {
                return ResourceManager.GetString("Cart.CartCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string Cart_Checkout {
            get {
                return ResourceManager.GetString("Cart.Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cart.
        /// </summary>
        public static string Cart_ClearCart {
            get {
                return ResourceManager.GetString("Cart.ClearCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear entire cart?.
        /// </summary>
        public static string Cart_ClearCartConfirm {
            get {
                return ResourceManager.GetString("Cart.ClearCartConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error clearing cart.
        /// </summary>
        public static string Cart_ClearError {
            get {
                return ResourceManager.GetString("Cart.ClearError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Shopping.
        /// </summary>
        public static string Cart_ContinueShopping {
            get {
                return ResourceManager.GetString("Cart.ContinueShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customizations.
        /// </summary>
        public static string Cart_Customizations {
            get {
                return ResourceManager.GetString("Cart.Customizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string Cart_DeliveryFee {
            get {
                return ResourceManager.GetString("Cart.DeliveryFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cart is empty.
        /// </summary>
        public static string Cart_Empty {
            get {
                return ResourceManager.GetString("Cart.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add dishes from restaurant menus.
        /// </summary>
        public static string Cart_EmptyText {
            get {
                return ResourceManager.GetString("Cart.EmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item removed from cart.
        /// </summary>
        public static string Cart_ItemRemoved {
            get {
                return ResourceManager.GetString("Cart.ItemRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Cost.
        /// </summary>
        public static string Cart_ItemsCost {
            get {
                return ResourceManager.GetString("Cart.ItemsCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Summary.
        /// </summary>
        public static string Cart_OrderSummary {
            get {
                return ResourceManager.GetString("Cart.OrderSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per piece.
        /// </summary>
        public static string Cart_PerPiece {
            get {
                return ResourceManager.GetString("Cart.PerPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity updated.
        /// </summary>
        public static string Cart_QuantityUpdated {
            get {
                return ResourceManager.GetString("Cart.QuantityUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Cart_Remove {
            get {
                return ResourceManager.GetString("Cart.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error removing item.
        /// </summary>
        public static string Cart_RemoveError {
            get {
                return ResourceManager.GetString("Cart.RemoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this item from cart?.
        /// </summary>
        public static string Cart_RemoveItemConfirm {
            get {
                return ResourceManager.GetString("Cart.RemoveItemConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Cart_Title {
            get {
                return ResourceManager.GetString("Cart.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Cart_Total {
            get {
                return ResourceManager.GetString("Cart.Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating quantity.
        /// </summary>
        public static string Cart_UpdateError {
            get {
                return ResourceManager.GetString("Cart.UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Cart.
        /// </summary>
        public static string Cart_YourCart {
            get {
                return ResourceManager.GetString("Cart.YourCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Common_Back {
            get {
                return ResourceManager.GetString("Common.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2025 - Food Delivery Platform.
        /// </summary>
        public static string Common_Copyright {
            get {
                return ResourceManager.GetString("Common.Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Common_Details {
            get {
                return ResourceManager.GetString("Common.Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Common_Edit {
            get {
                return ResourceManager.GetString("Common.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Delivery.
        /// </summary>
        public static string Common_FoodDelivery {
            get {
                return ResourceManager.GetString("Common.FoodDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Delivery Platform.
        /// </summary>
        public static string Common_FoodDeliveryPlatform {
            get {
                return ResourceManager.GetString("Common.FoodDeliveryPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Common_Search {
            get {
                return ResourceManager.GetString("Common.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Common_Submit {
            get {
                return ResourceManager.GetString("Common.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Users.
        /// </summary>
        public static string Home_ActiveUsers {
            get {
                return ResourceManager.GetString("Home.ActiveUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Access.
        /// </summary>
        public static string Home_AdminAccess {
            get {
                return ResourceManager.GetString("Home.AdminAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have administrator rights. Go to the control panel..
        /// </summary>
        public static string Home_AdminAccessText {
            get {
                return ResourceManager.GetString("Home.AdminAccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American.
        /// </summary>
        public static string Home_American {
            get {
                return ResourceManager.GetString("Home.American", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burgers, steaks.
        /// </summary>
        public static string Home_AmericanText {
            get {
                return ResourceManager.GetString("Home.AmericanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Rating.
        /// </summary>
        public static string Home_AverageRating {
            get {
                return ResourceManager.GetString("Home.AverageRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy Payment.
        /// </summary>
        public static string Home_EasyPayment {
            get {
                return ResourceManager.GetString("Home.EasyPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay online with card or cash on delivery. Secure transactions.
        /// </summary>
        public static string Home_EasyPaymentText {
            get {
                return ResourceManager.GetString("Home.EasyPaymentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Delivery.
        /// </summary>
        public static string Home_FastDelivery {
            get {
                return ResourceManager.GetString("Home.FastDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average delivery time 30-40 minutes. Track your order in real time.
        /// </summary>
        public static string Home_FastDeliveryText {
            get {
                return ResourceManager.GetString("Home.FastDeliveryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order food from the best restaurants in your city quickly and conveniently.
        /// </summary>
        public static string Home_HeroSubtitle {
            get {
                return ResourceManager.GetString("Home.HeroSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Ordering and Delivery Platform.
        /// </summary>
        public static string Home_HeroTitle {
            get {
                return ResourceManager.GetString("Home.HeroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How It Works.
        /// </summary>
        public static string Home_HowItWorks {
            get {
                return ResourceManager.GetString("Home.HowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordering food is easy — just 4 simple steps.
        /// </summary>
        public static string Home_HowItWorksSubtitle {
            get {
                return ResourceManager.GetString("Home.HowItWorksSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string Home_Italian {
            get {
                return ResourceManager.GetString("Home.Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza, pasta.
        /// </summary>
        public static string Home_ItalianText {
            get {
                return ResourceManager.GetString("Home.ItalianText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string Home_Japanese {
            get {
                return ResourceManager.GetString("Home.Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sushi, rolls.
        /// </summary>
        public static string Home_JapaneseText {
            get {
                return ResourceManager.GetString("Home.JapaneseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join thousands of satisfied customers.
        /// </summary>
        public static string Home_JoinThousands {
            get {
                return ResourceManager.GetString("Home.JoinThousands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Admin Panel.
        /// </summary>
        public static string Home_OpenAdminPanel {
            get {
                return ResourceManager.GetString("Home.OpenAdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders Per Month.
        /// </summary>
        public static string Home_OrdersPerMonth {
            get {
                return ResourceManager.GetString("Home.OrdersPerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Cuisines.
        /// </summary>
        public static string Home_PopularCuisines {
            get {
                return ResourceManager.GetString("Home.PopularCuisines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your favorite cuisine.
        /// </summary>
        public static string Home_PopularCuisinesSubtitle {
            get {
                return ResourceManager.GetString("Home.PopularCuisinesSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to Order?.
        /// </summary>
        public static string Home_ReadyToOrder {
            get {
                return ResourceManager.GetString("Home.ReadyToOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurants.
        /// </summary>
        public static string Home_Restaurants {
            get {
                return ResourceManager.GetString("Home.Restaurants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse the menu and select your favorite dishes.
        /// </summary>
        public static string Home_Step1Text {
            get {
                return ResourceManager.GetString("Home.Step1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Restaurant.
        /// </summary>
        public static string Home_Step1Title {
            get {
                return ResourceManager.GetString("Home.Step1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize dishes to your taste.
        /// </summary>
        public static string Home_Step2Text {
            get {
                return ResourceManager.GetString("Home.Step2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Cart.
        /// </summary>
        public static string Home_Step2Title {
            get {
                return ResourceManager.GetString("Home.Step2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter address and payment method.
        /// </summary>
        public static string Home_Step3Text {
            get {
                return ResourceManager.GetString("Home.Step3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Order.
        /// </summary>
        public static string Home_Step3Title {
            get {
                return ResourceManager.GetString("Home.Step3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy delicious food!.
        /// </summary>
        public static string Home_Step4Text {
            get {
                return ResourceManager.GetString("Home.Step4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Delivery.
        /// </summary>
        public static string Home_Step4Title {
            get {
                return ResourceManager.GetString("Home.Step4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        public static string Home_Ukrainian {
            get {
                return ResourceManager.GetString("Home.Ukrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dumplings, borsch.
        /// </summary>
        public static string Home_UkrainianText {
            get {
                return ResourceManager.GetString("Home.UkrainianText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Restaurants.
        /// </summary>
        public static string Home_ViewRestaurants {
            get {
                return ResourceManager.GetString("Home.ViewRestaurants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Choose Us.
        /// </summary>
        public static string Home_WhyChooseUs {
            get {
                return ResourceManager.GetString("Home.WhyChooseUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best platform for ordering food online.
        /// </summary>
        public static string Home_WhyChooseUsSubtitle {
            get {
                return ResourceManager.GetString("Home.WhyChooseUsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wide Selection of Restaurants.
        /// </summary>
        public static string Home_WideSelection {
            get {
                return ResourceManager.GetString("Home.WideSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over 100+ restaurants with various cuisines: Italian, Japanese, Ukrainian, American and more.
        /// </summary>
        public static string Home_WideSelectionText {
            get {
                return ResourceManager.GetString("Home.WideSelectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Language_English {
            get {
                return ResourceManager.GetString("Language.English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        public static string Language_German {
            get {
                return ResourceManager.GetString("Language.German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language_SelectLanguage {
            get {
                return ResourceManager.GetString("Language.SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Українська.
        /// </summary>
        public static string Language_Ukrainian {
            get {
                return ResourceManager.GetString("Language.Ukrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Panel.
        /// </summary>
        public static string Nav_AdminPanel {
            get {
                return ResourceManager.GetString("Nav.AdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Nav_Cart {
            get {
                return ResourceManager.GetString("Nav.Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Nav_Login {
            get {
                return ResourceManager.GetString("Nav.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Nav_Logout {
            get {
                return ResourceManager.GetString("Nav.Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Addresses.
        /// </summary>
        public static string Nav_MyAddresses {
            get {
                return ResourceManager.GetString("Nav.MyAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Orders.
        /// </summary>
        public static string Nav_MyOrders {
            get {
                return ResourceManager.GetString("Nav.MyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string Nav_MyProfile {
            get {
                return ResourceManager.GetString("Nav.MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Reviews.
        /// </summary>
        public static string Nav_MyReviews {
            get {
                return ResourceManager.GetString("Nav.MyReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Nav_Register {
            get {
                return ResourceManager.GetString("Nav.Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurants.
        /// </summary>
        public static string Nav_Restaurants {
            get {
                return ResourceManager.GetString("Nav.Restaurants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string OrderStatus_Cancelled {
            get {
                return ResourceManager.GetString("OrderStatus.Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string OrderStatus_Confirmed {
            get {
                return ResourceManager.GetString("OrderStatus.Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        public static string OrderStatus_Delivered {
            get {
                return ResourceManager.GetString("OrderStatus.Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out for Delivery.
        /// </summary>
        public static string OrderStatus_OutForDelivery {
            get {
                return ResourceManager.GetString("OrderStatus.OutForDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string OrderStatus_Pending {
            get {
                return ResourceManager.GetString("OrderStatus.Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing.
        /// </summary>
        public static string OrderStatus_Preparing {
            get {
                return ResourceManager.GetString("OrderStatus.Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string OrderStatus_Ready {
            get {
                return ResourceManager.GetString("OrderStatus.Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Cuisines.
        /// </summary>
        public static string Restaurant_AllCuisines {
            get {
                return ResourceManager.GetString("Restaurant.AllCuisines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string Restaurant_Any {
            get {
                return ResourceManager.GetString("Restaurant.Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Filters.
        /// </summary>
        public static string Restaurant_ApplyFilters {
            get {
                return ResourceManager.GetString("Restaurant.ApplyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Restaurant_Cost {
            get {
                return ResourceManager.GetString("Restaurant.Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuisine Type.
        /// </summary>
        public static string Restaurant_CuisineType {
            get {
                return ResourceManager.GetString("Restaurant.CuisineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string Restaurant_Delivery {
            get {
                return ResourceManager.GetString("Restaurant.Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Time.
        /// </summary>
        public static string Restaurant_DeliveryTime {
            get {
                return ResourceManager.GetString("Restaurant.DeliveryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        public static string Restaurant_Found {
            get {
                return ResourceManager.GetString("Restaurant.Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. Order.
        /// </summary>
        public static string Restaurant_MinOrder {
            get {
                return ResourceManager.GetString("Restaurant.MinOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. Rating.
        /// </summary>
        public static string Restaurant_MinRating {
            get {
                return ResourceManager.GetString("Restaurant.MinRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Restaurant_Name {
            get {
                return ResourceManager.GetString("Restaurant.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Restaurants Found.
        /// </summary>
        public static string Restaurant_NotFound {
            get {
                return ResourceManager.GetString("Restaurant.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try changing search parameters or reset filters.
        /// </summary>
        public static string Restaurant_NotFoundText {
            get {
                return ResourceManager.GetString("Restaurant.NotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Restaurants.
        /// </summary>
        public static string Restaurant_OurRestaurants {
            get {
                return ResourceManager.GetString("Restaurant.OurRestaurants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Restaurant_Rating {
            get {
                return ResourceManager.GetString("Restaurant.Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Restaurant_Reset {
            get {
                return ResourceManager.GetString("Restaurant.Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        public static string Restaurant_Restaurant {
            get {
                return ResourceManager.GetString("Restaurant.Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restaurants.
        /// </summary>
        public static string Restaurant_Restaurants {
            get {
                return ResourceManager.GetString("Restaurant.Restaurants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant name or cuisine....
        /// </summary>
        public static string Restaurant_SearchPlaceholder {
            get {
                return ResourceManager.GetString("Restaurant.SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        public static string Restaurant_SortBy {
            get {
                return ResourceManager.GetString("Restaurant.SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Restaurant_Time {
            get {
                return ResourceManager.GetString("Restaurant.Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurants.
        /// </summary>
        public static string Restaurant_Title {
            get {
                return ResourceManager.GetString("Restaurant.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to 30 min.
        /// </summary>
        public static string Restaurant_UpTo30Min {
            get {
                return ResourceManager.GetString("Restaurant.UpTo30Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to 45 min.
        /// </summary>
        public static string Restaurant_UpTo45Min {
            get {
                return ResourceManager.GetString("Restaurant.UpTo45Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to 60 min.
        /// </summary>
        public static string Restaurant_UpTo60Min {
            get {
                return ResourceManager.GetString("Restaurant.UpTo60Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Menu.
        /// </summary>
        public static string Restaurant_ViewMenu {
            get {
                return ResourceManager.GetString("Restaurant.ViewMenu", resourceCulture);
            }
        }
    }
}
